### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by drawdesky** [davidegironi/dentned#5]
Hello and thank you for sharing your project.

I have some issues tring to login.
Ive installed sql server 2019 express and sql server management studio.
Ive already restore the database on sql server management studio. After that I configured the server config file. 
But keep telling me theres an error trying to connect to database.

    <add name="dentnedEntities" connectionString="metadata=res://*/Entity.Model_dentned.csdl|res://*/Entity.Model_dentned.ssdl|res://*/Entity.Model_dentned.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=DESKTOP-B8LBQPS\SQLEXPRESS;initial catalog=dentend;user id=DESKTOP-B8LBQPS\biode ;password=PASS;MultipleActiveResultSets=True;App=EntityFramework&quot;" providerName="System.Data.EntityClient"/>
  </connectionStrings>

Hope you can help me

Thanks 

Edd

**Comment by davidegironi** [comment]
Hello @drawdesky,
if you are connecting to you localhost SQL express as i suppose, you could use Integrated Security, the connection string change from 
`metadata=res://*/Entity.Model_dentned.csdl|res://*/Entity.Model_dentned.ssdl|res://*/Entity.Model_dentned.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=DATASOURCE;initial catalog=INITIALCATALOG;user id=USERID;password=PASSWORD;MultipleActiveResultSets=True;App=EntityFramework&quot;`
to
`metadata=res://*/Entity.Model_dentned.csdl|res://*/Entity.Model_dentned.ssdl|res://*/Entity.Model_dentned.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=DATASOURCE;initial catalog=INITIALCATALOG;Integrated Security=true;MultipleActiveResultSets=True;App=EntityFramework&quot;`

so your Connection String should look like
`metadata=res://*/Entity.Model_dentned.csdl|res://*/Entity.Model_dentned.ssdl|res://*/Entity.Model_dentned.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=DESKTOP-B8LBQPS\SQLEXPRESS;initial catalog=dentend;Integrated Security=true;MultipleActiveResultSets=True;App=EntityFramework&quot;`

otherwise you have to enable the SQL Server Authentication, and create a SQL Server user
https://docs.microsoft.com/en-us/sql/relational-databases/security/choose-an-authentication-mode?view=sql-server-ver15
https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/create-a-login?view=sql-server-ver15

Hope this helps, let me know if this works.

**Comment by drawdesky** [comment]
Hello @davidegironi and thank you for your help.
I've already tried everything you said and I'm still having error to connect to database.
First I changed the user and password to "Integrated security = True" tried and the error connection appeared.
Later I changed to sql server authentication and created a user and pass in SQL MS, configured these values in the config file and still having this error.
Tried again with integrated security and still with the error.
In the other hand I see two similar files in the bin folder, dentned.exe.config and dentnedser.exe.config.Ive changed the values in these two files since the connection string appears in the two. I think I'm missing something else.

Thanks again!

**Comment by davidegironi** [comment]
@drawdesky it is for sure something related to the connection string and you SQL Express configuration. You can build a new sample C# project at add an entity model from database, selecting you database, this will create the connection string on you app configuration.
dentned.exe.config is the configuration file for dentned.exe (the main desktop software), dentnedser.exe.config is the configuration file for the dentned service (dentnedser.exe).

**Comment by drawdesky** [comment]
Thanks davide for your comments. Unfortunately I'm not very much familiarized with C# or SQL Express. I think that is why is in some case difficult for me to configure the program. I'll try my best and watch some videos in youtube and see if I can fix the issue. If it's possible in any time for you to make a video installation instructions it would be excellent.  Thanks again for your help.

**Comment by davidegironi** [comment]
Great! You are going to learn something new, and that's always a good thing!
Take a look here https://www.youtube.com/watch?v=K4x6eoG7hwY it may helps.
