### ISSUE TITLE
How to setup Report password ?

### ISSUE THREAD

**Issue by Shahabh786** [davidegironi/dentned#9]
Hi,

I'm not sure if we have a default password or we can setup our own to view the reports.

Please guide

**Comment by davidegironi** [comment]
Hello,
In order to set a custom password for the Report form, you should run the GetEncryptedPasswords.bat script. Then replace the value for the key passwordProtectedReports on the application .config file.
You can also protect individial forms with the other generated password, but you have to list which form to protect in the passwordProtectedForms value of application .config file.
Hope this helps.

**Comment by Shahabh786** [comment]
Thank you so much! It helped
